###
POST http://localhost:8080/posts
Content-Type: application/json

{
  "title": "Программирование - это заголовок",
  "content": "Программирование — это искусство создания решений через код. Это контент.",
  "authorId": 1
}

<> 2025-09-09T090512.200.json
<> 2025-09-09T090455.200.json
<> 2025-09-09T090452.200.json
<> 2025-09-09T090411.200.json
